// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/board/all-boards/{projectId}": {
            "get": {
                "description": "get all boards",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Board"
                ],
                "summary": "get all boards",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/board/{boardId}": {
            "get": {
                "description": "get board",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Board"
                ],
                "summary": "get board",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "update board",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Board"
                ],
                "summary": "update board",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BoardDTO",
                        "name": "BoardDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/boardDTO.BoardDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete board",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Board"
                ],
                "summary": "delete board",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Board ID",
                        "name": "boardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/board/{projectId}": {
            "post": {
                "description": "create new board",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Board"
                ],
                "summary": "create new board",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "BoardDTO",
                        "name": "BoardDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/boardDTO.BoardDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/column": {
            "post": {
                "description": "update column order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ColumnData"
                ],
                "summary": "update column order",
                "parameters": [
                    {
                        "description": "UpdateColumnOrderDTO",
                        "name": "updateColumnOrderDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/columnDTO.UpdateColumnOrderDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/column/{boardID}": {
            "post": {
                "description": "create new board",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ColumnData"
                ],
                "summary": "create new column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "boardID",
                        "name": "boardID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ColumnDTO",
                        "name": "ColumnDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/columnDTO.ColumnDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/column/{columnID}": {
            "put": {
                "description": "create new board",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ColumnData"
                ],
                "summary": "create new column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "columnID",
                        "name": "columnID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ColumnDTO",
                        "name": "ColumnDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/columnDTO.ColumnDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete column",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ColumnData"
                ],
                "summary": "delete column",
                "parameters": [
                    {
                        "type": "string",
                        "description": "columnID",
                        "name": "columnID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "user login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "description": "LoginDTO",
                        "name": "loginDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDTO.LoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responseDTO.LoginResponse"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "get user profile",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/project": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "create new project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "create new project",
                "parameters": [
                    {
                        "description": "newProjectDTO",
                        "name": "newProjectDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/projectDTO.ProjectDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/responseDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responseDTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/project/{projectId}": {
            "get": {
                "description": "update project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "get project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "update project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "update project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "newProjectDTO",
                        "name": "newProjectDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/projectDTO.ProjectDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "delete project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "user register",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "register",
                "parameters": [
                    {
                        "description": "RegisterDTO",
                        "name": "registerDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDTO.RegisterDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/task": {
            "get": {
                "description": "get all tasks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "get all tasks",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/task/column/{columnId}/task/{taskId}": {
            "put": {
                "description": "update task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "update task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ColumnData ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/task/{columnId}": {
            "post": {
                "description": "create new task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "create new task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ColumnData ID",
                        "name": "columnId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "newTaskDTO",
                        "name": "newTaskDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/taskDTO.TaskDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/task/{taskId}": {
            "get": {
                "description": "get task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "get task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "description": "update task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "update task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "newTaskDTO",
                        "name": "newTaskDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/taskDTO.TaskDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "delete task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/task/{taskId}/complete": {
            "put": {
                "description": "update task",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "update task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "boardDTO.BoardDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "columnDTO.ColumnDTO": {
            "type": "object",
            "properties": {
                "is_final": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "order": {
                    "description": "порядок начинается с 0",
                    "type": "integer"
                }
            }
        },
        "columnDTO.UpdateColumnOrderDTO": {
            "type": "object",
            "properties": {
                "first_column_id": {
                    "type": "string"
                },
                "first_order": {
                    "type": "integer"
                },
                "second_column_id": {
                    "type": "string"
                },
                "second_order": {
                    "type": "integer"
                }
            }
        },
        "projectDTO.ProjectDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "responseDTO.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid project data"
                }
            }
        },
        "responseDTO.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "tokenType": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "taskDTO.TaskDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "userDTO.LoginDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "userDTO.RegisterDTO": {
            "type": "object",
            "required": [
                "email",
                "password",
                "user_name"
            ],
            "properties": {
                "email": {
                    "description": "валидация",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                },
                "user_name": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите JWT токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Project manager with Essence core",
	Description:      "Серверная часть прототипа системы управления проектами с ядром Essence",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
