definitions:
  errors.Status:
    enum:
    - 1
    - 2
    - 3
    - 4
    - 5
    type: integer
    x-enum-comments:
      BadRequest: "400"
      Forbidden: "403"
      NotFound: "404"
      Unauthorized: "401"
      UnsupportedMediaType: "415"
    x-enum-descriptions:
    - "400"
    - "401"
    - "403"
    - "404"
    - "415"
    x-enum-varnames:
    - BadRequest
    - Unauthorized
    - Forbidden
    - NotFound
    - UnsupportedMediaType
  errors.StatusError:
    properties:
      message:
        type: string
      status:
        $ref: '#/definitions/errors.Status'
    type: object
info:
  contact: {}
  description: Серверная часть прототипа системы управления проектами с ядром Essence
  title: Project manager with Essence core
  version: "1.0"
paths:
  /api/get:
    get:
      consumes:
      - application/json
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.StatusError'
      summary: Show an account
      tags:
      - accounts
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
